name: CI Setup
on:
  - push
  - pull_request
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - name: Setup node 12
        uses: actions/setup-node@v1
        with: {node-version: 12.x}
      - run: npm ci
  Test:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Load node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Setup node 12
        uses: actions/setup-node@v1
        with: {node-version: 12.x}
      - run: npm test
